project_id = "zrxwrdkodjlnkupfqwfa"

[functions.upload-image]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.compare-faces]
verify_jwt = false

[functions.compare-faces-public]
verify_jwt = false